version: '3.9'
services:
  db:
    container_name: db
    build:
      dockerfile: Dockerfile
      context: src/store
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - db

  nest_app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - /app
      - /app/node_modules
    env_file:
    - .env
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    restart: always
    depends_on:
      - db
    networks:
      - db

volumes:
  db:

networks:
  db:
    driver: bridge