version: '3.9'
services:
  db:
    container_name: db
    build:
      dockerfile: Dockerfile
      context: src/db
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - nodejs-network

  nest_app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /app
      - /app/node_modules
    env_file:
    - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - nodejs-network

volumes:
  db:

networks:
  nodejs-network:
    driver: bridge